In [ ]:
class className:
    #some functions and variables
    #function--used to perform cetain activity
    #variable--Data(memory)

In [1]:
def test():
    return
test()

In [4]:
class Demo:
    def test(self):
        print("test() fot the class")
        return
obj=Demo()
obj.test()

test() fot the class


In [10]:
class Demo1():
    def fact(self,n):
        #return factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
    def nfjjfn()
    
p1=Demo1()
print(p1.fact(5))#120

120


In [18]:
#Methord
#def test(self,pa)
class Demo2:
    def _init_(self,p1,p2):
        self.a=p1
        self.b=p2
    
    def add(s):
        return s.a+s.b
    
c1=Demo2()
c1._init_(100,200)
print(c1.add())

300


In [2]:
#test
import re 
sum=0
pattern='back'
if re.match(pattern,'backup.txt'):
    sum+=1
if re.match(pattern,'text.back'):
    sum+=2
if re.match(pattern,'backup.txt'):
    sum+=4
if re.match(pattern,'text.back'):
    sum+=8
    
print(sum)

5


In [21]:
#some inheritance
class Person(object):
    #Constructor
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
#derived class
class Employee(Person):
    def isEmployee(self):
        return True
    
emp=Person("Anil")
print(emp.getName(),emp.isEmployee())

emp1= Employee("Raja")
print(emp1.getName(),emp1.isEmployee())


Anil False
Raja True


## NUMPY

In [22]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [4]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [7]:
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(2, 3)
(3, 2)


In [6]:
#Re shape the given array
#numpy.reshape(arrayName,reshape,order='c')
import numpy as np
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
#np.ones(shape,dtype=float,order='c')
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [9]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [12]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=5
np.asarray(A)[3][3]=23
print(A)

[[ 1  1  1  1]
 [ 1  1  1  5]
 [ 1  1  1  1]
 [ 1  1  1 23]]


In [13]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,2])


slicing column: [3 6]


In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])



slicing column: [2 5]


In [15]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row:",a1[1])



second row: [4 5 6]


In [16]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])



first row: [1 2 3]


In [17]:
a1=np.random.normal(5,1,10)
print(a1)
print(np.min(a1))
print(np.max(a1))
print(np.mean(a1))
print(np.median(a1))

[4.06956435 6.81922255 5.16075173 4.17081398 4.25419937 5.23745537
 5.56183156 4.14348363 4.73081988 4.20712356]
4.069564354321039
6.819222550114593
4.835526598067008
4.492509624160341


In [20]:
#multiply of 1D array
#numpy.dot(x,y)--

c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [21]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [25]:
b1=np.array([(1,5),[6,9]])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])